platform:ios,"9.0"

target "SmartLight" do
use_frameworks!
pod 'SnapKit'
pod 'Then'
pod 'Toaster'
pod 'EFQRCode', '~> 5.0.0'
pod 'Alamofire'
pod 'IQKeyboardManagerSwift'
pod 'CocoaAsyncSocket'
pod 'XCGLogger'
pod 'Bugly'

end
